# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

ruby '>= 2.7'

gem 'grpc', '~> 1.59'
gem 'google-protobuf', '~> 3.25', '>= 3.25.5'
gem 'multi_json', '~> 1.15'
